### ISSUE TITLE
Outdated chokidar version causing dependency vulnerability

### ISSUE THREAD

**Issue by marcioaffonso** [kmagiera/babel-watch#104]
After running `npm audit`, you can see a vulnerability in `babel-watch > chokidar > anymatch > micromatch > braces`

Chokidar version should be updated.

**Comment by STRML** [comment]
I'm not seeing that on a reinstall. Try clearing your lockfile & reinstall babel-watch.

**Comment by stefee** [comment]
Was this resolved by https://github.com/kmagiera/babel-watch/pull/97 ? Has this been released yet?

**Comment by marcioaffonso** [comment]
@STRML, @srilq the version `7.0.0`(latest) in NPM is using chokidar@1.4.3.

**Comment by STRML** [comment]
Ah yes. It is fixed in #97 but @kmagiera has not yet merged. Chokidar@3 is already out and I'll give it a test, we can jump right to it which saves some CPU cycles.

**Comment by marcioaffonso** [comment]
@kmagiera @STRML, could you please publish the PR https://github.com/kmagiera/babel-watch/pull/97?

People are moving away from this package as you can see in https://github.com/iamogbz/bot-slacker/pull/33/files because this is generating a vulnerability in the dependencies.

**Comment by STRML** [comment]
I can't publish. It's on @kmagiera
