### ISSUE TITLE
Source maps missing

### ISSUE THREAD

**Issue by msaspence** [kmagiera/babel-watch#110]
If I run `npx babel-node ./src/index.js --inspect=0.0.0.0:9223` I see a source maps in the Chrome dev tools. 

If however I run `npx babel-watch .src/index.js --inspect=0.0.0.0:9223` the files are transpired and run file however there are no source map comments in the file.

I have `sourceMaps: 'both',` in my `babel.config.js` file

**Comment by clintonmedbery** [comment]
Same problem here @kmagiera

**Comment by STRML** [comment]
Fixed in `7.3.0` through #118.
