### ISSUE TITLE
Release needed

### ISSUE THREAD

**Issue by phawxby** [kmagiera/babel-watch#114]
@kmagiera it looks like there has been a whole bunch of PR's merged (17 I think) in since [the last release in 2017](https://github.com/kmagiera/babel-watch/releases/tag/v2.0.7), any chance of a update being published? Thanks.

**Comment by STRML** [comment]
I've been trying to get npm publish permissions from @kmagiera for about two years now, despite having commit permission here.

**Comment by phawxby** [comment]
@STRML dang. I've just messaged him on Twitter to see if he's more likely to see it there.

**Comment by STRML** [comment]
Release is done! [`v7.1.0`](https://github.com/kmagiera/babel-watch/releases/tag/v7.1.0)
