### ISSUE TITLE
How to disable ">>> RESTARTING <<<" message?

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [kmagiera/babel-watch#115]
`--quiet` and `-q` flags like nodemon not working.

How to disable ">>> RESTARTING <<<" message?

p.s. Please add an option that would also clear the console before restarting =)
I would like to just press ctrl + s and see in the console ONLY the result of the current iteration. If I write 200 console.log's in my app (I do this often), then I want scroll to top of output, and understand where it starts. And must not see the results of previous iterations.  ^ _ ^ if you understand what I mean.

**Comment by STRML** [comment]
I think a clear console option is a good idea. PRs welcome.

**Comment by STRML** [comment]
Fixed in `7.2.0` (option `--clear-console`).

**Comment by MaxmaxmaximusAWS** [comment]
thank you very much
