### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by jhessin** [kmagiera/babel-watch#117]
Expected behavior: Running babel-watch should give the same result as running babel directly.

Actual behavior: I get an error with babel-watch that I don't get with babel.

```
ReferenceError: document is not defined
```
if I run babel directly this error doesn't occur.

The only thing I'm currently using babel for is stripping flow annotations.

**Comment by STRML** [comment]
Sorry, this is not something we can reproduce without much more detail. There is nothing about `babel-watch` that should require a DOM.

**Comment by jhessin** [comment]
Gave Babel the boot. Using typescript now.
