### ISSUE TITLE
ipranges.json in NPM module

### ISSUE THREAD

**Issue by dobesv** [kmagiera/babel-watch#119]
It seems like the NPM module has this extra file, `ip-ranges.json` in it for some reason.

**Comment by STRML** [comment]
Thanks much. Looks like a little bit of my day to day made it in the package. Allowlists over denylists, ladies and gentlemen.

**Comment by STRML** [comment]
Fixed in v7.3.1 which is live now on npm. Size is only 31.6kB unpacked versus 705.9kB in 7.3.0.
