### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by sebdeckers** [kmagiera/babel-watch#12]
Is it possible to pass the `--debug` and `--debug-break` arguments? That would allow using `babel-watch` with debugging tools like `node-inspector` or VS Code. Both `node` and `babel-node` accept these arguments.

**Comment by kmagiera** [comment]
@cbas Yes, it is possible to run app with `--debug` flag although I haven't yet added that to the documentation. You can try running your app like this:

```
babel-watch -- app.js --debug
```

Node that there is `--` that should be added between options that you pass to babel-watch and options you want your program to use.

Option `--debug-brk` won't work at the moment as there is a small piece of code that runs within the node process before we start loading the app and you perhaps don't want your debugger to pause on that loader script.

I plan on investing some time to streamline debugging with `babel-watch` and already have a few ideas but will appreciate any suggestions!
