### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "fd" argument must be of type number

### ISSUE THREAD

**Issue by BenSaus** [kmagiera/babel-watch#123]
Hi guys, I keep getting the following error and I'm running out of ideas. I'm hoping you have some ideas or hints for me

```
$ npm run start-w

> claudia-express@1.0.0 start-w Z:\bk\Zd\firstdaySetup\ZBackend
> set DEPLOYMENT=development&&babel-watch src/app

Winston started: false Z:\bk\Zd\firstdaySetup\ZBackend/logs/development.log
Starting Database: Zd_development
>>> RESTARTING <<<
Z:\bk\Zd\firstdaySetup\ZBackend\node_modules\babel-watch\babel-watch.js:300
          throw error;
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "fd" argument must be of type number. Received type undefined      
    at Object.writeSync (fs.js:567:3)
    at Z:\bk\Zd\firstdaySetup\ZBackend\node_modules\babel-watch\babel-watch.js:291:12
    at Z:\bk\Zd\firstdaySetup\ZBackend\node_modules\babel-watch\babel-watch.js:191:7
    at Z:\bk\Zd\firstdaySetup\ZBackend\node_modules\babel-watch\babel-watch.js:345:5
    at Z:\bk\Zd\firstdaySetup\ZBackend\node_modules\babel-core\lib\api\node.js:143:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! claudia-express@1.0.0 start-w: `set DEPLOYMENT=development&&babel-watch src/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the claudia-express@1.0.0 start-w script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.       

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ben\AppData\Roaming\npm-cache\_logs\2021-05-06T16_56_38_183Z-debug.log
```

This same exact repo branch ect. works perfectly on another win10 computer. On the problem desktop, I have deleted the repo multiple times, cleared npm cache, verified npm cache, deleted node_modules many times, tried npm ci, reinstalled node to an identical version to the working system. Here's some info:

Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Node: v12.4.0  <-- same results on node 14
"babel-watch": "^2.0.7",
"babel-cli": "^6.26.0",
"babel-core": "^6.26.3",
"babel-plugin-root-import": "^6.4.1",
"babel-preset-es2015": "^6.24.1",

I thought it could be a permissions issue, so I ensured nothing was read only, that didn't change anything. I printed out the particular file that babel-watch is trying to write to and it changes every run. 

Any help is appreciated. Thanks

**Comment by STRML** [comment]
The latest version is `7.4.1`, not `2.0.7`.

We don't actively support using babel 6 anymore, it's long, *long* dead.

**Comment by BenSaus** [comment]
Well I'm just a little out of date. I didn't realize. Thanks
