### ISSUE TITLE
NODE_PATH not working?

### ISSUE THREAD

**Issue by ericfong** [kmagiera/babel-watch#13]
seem to me that NODE_PATH is not pass down for

NODE_PATH=PATH babel-watch app.js

**Comment by kmagiera** [comment]
Hey @ericfong thanks for reporting!

Would you be able to provide some additional details on your issue? I've tried to reproduce it but was not able to. Here are the things I've tried:

1) Have `console.log(process.env.NODE_PATH);` in my `app.js` then run `NODE_PATH=test babel-watch app.js` -> result was that the env variable has been printed out correctly
2) Have `require('bar')` in my `app.js` code where `bar.js` was placed under `foo` directory and run `NODE_PATH=foo babel-watch app.js` -> require worked as expected and I was able to require files from under the `foo` directory.

I'll close this issue, but please feel free to reopen it once you have time to get back with a repro scenario
