### ISSUE TITLE
Changes in views are not being watched

### ISSUE THREAD

**Issue by imns** [kmagiera/babel-watch#14]
First off, great library (thank you)!

I'm having some trouble getting this to work when a change is made in one of my view files.  I'm using express and nunjucks (html) templates.  If I change a `.js` file, it restarts lightning fast, but if I change one of my `.html` template files it doesn't restart.

I've tried playing around with the extensions flag, but haven't had any luck.  

Any help would be great.  Thanks

**Comment by pfhayes** [comment]
This issue is addressed in https://github.com/kmagiera/babel-watch/pull/20

**Comment by kmagiera** [comment]
I've pushed an update that will hopefully resolve this issue, please check 2.0.3-rc0 and feel free to reopen the issue if you're still experiencing the problem

**Comment by artf** [comment]
It works now, thanks @kmagiera
