### ISSUE TITLE
Degradation after refactoring and another uncaught error location

### ISSUE THREAD

**Issue by IMalyugin** [kmagiera/babel-watch#147]
Last commit introduced a degradation here:
https://github.com/kmagiera/babel-watch/commit/e8e60affd9fc06341c967a4020cd63b4fa9f7173#diff-3ff4a3ee3a0bfeb4fbf652e6a71273903130d817040ffac875ac6540b98e5907R438

If files are ignored (aka no source) we should still send it the runner, so they can be handled by defaultLoader.
With this new line, babel-watch refuses to require .json files.

There is yet another issue I found, that is unrelated to both last feature and refactoring. During babel compilation, only syntax errors are caught. Any other thrown error is typically ignored. Problem is that require.ext just causes an exception and it becomes unhandled.

Got both fixes ready in a pull request

@STRML ping

**Comment by STRML** [comment]
Thanks for finding, will merge & release after testing

**Comment by IMalyugin** [comment]
Works for me, launching an entire server:
- [x] restart on change
- [x] .json files
- [x] exceptions during execution

Although i think i have double errors during restart, gotta double check

**Comment by STRML** [comment]
I was getting double errors before this PR but now I'm actually getting obfuscation of the old error. I don't think it's good to introduce an `uncaughtException` error here as it will essentially leak into user code. Will fix.

**Comment by IMalyugin** [comment]
We could just capture and log error from require[ext].

As for the double error - nevermind, I'm getting it regardless.
