### ISSUE TITLE
Source maps problem

### ISSUE THREAD

**Issue by gpbl** [kmagiera/babel-watch#15]
Hi, first thanks for this module, it made my restarts much faster 👍 

However, my error stack traces show wrong line numbers. If i run the app with `babel-node --source-maps` the line numbers are correct. Does anybody else have this issue?

**Comment by niftylettuce** [comment]
I've got the same issue @gpbl, did you figure this out or an alternative?

**Comment by gpbl** [comment]
@niftylettuce not yet :(

**Comment by niftylettuce** [comment]
Perhaps it is related to this https://github.com/babel/example-node-server/issues/10#issuecomment-237761423 - you can just use `source-map-support` at the top of your file like we did there and got it working.

**Comment by kmagiera** [comment]
@niftylettuce @gpbl sorry for very late response. So @niftylettuce answer is correct (at least it could be one of the reasons you may be seeing this) – this problem may occur if you import `source-map-support` or some other library which does that (e.g. `babel-register`)

I'll prepare a patch that will give you a warning whenever that thing happens. I don't think we can ever circumvent this, but at least we can make it cleaner for the users to understand what's going on.

Thanks @gpbl for reporting and @niftylettuce for investigating this issue and for your answer

**Comment by kmagiera** [comment]
Have a fix for that here: https://github.com/kmagiera/babel-watch/commit/6ea1c10aca305b86e32415bb8e0c60cb182628c2

**Comment by kmagiera** [comment]
And I've just pushed an update to npmjs, please check 2.0.3-rc0 and reopen if you're still experiencing the issue
