### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by nullxone** [kmagiera/babel-watch#18]
Here are some notes I put together while trying to get debugging working. I'm looking for suggestions on how to get this to work.

**Environment**

osx 10.11.2
node v4.4.7
npm@3.10.3
node-inspector@0.12.8
babel-watch@2.0.2

**Node command line flag order**

Does not work: `node ./test.js --debug-brk`
Works: `node --debug-brk ./test.js`

Ref: https://github.com/nodejs/node/blob/master/src/node.cc#L3420

**Cannot change order of flags passed to babel-watch**

Babel watch thinks that the first argument in `babel-watch --debug-brk ./test.js` is a file.
The offending three lines begin at https://github.com/kmagiera/babel-watch/blob/master/babel-watch.js#L92

**Args passed to babel watch don't seem to influence node arguments on spawned node process (forking the runner.js script)**

Am I correct in understanding that in runner.js, runMain just loads the modules?
Ref: https://github.com/nodejs/node/blob/master/lib/module.js#L573
If this is true, then we cannot expect node arguments to be propagated at the point runMain is called.
Ref: https://github.com/kmagiera/babel-watch/blob/master/runner.js#L87

**Alternative attempt at passing node arguments to child process**

Changing https://github.com/kmagiera/babel-watch/blob/master/babel-watch.js#L240 to
`const app = fork(path.resolve(__dirname, 'runner.js'), {execArgv: ['--debug-brk']});` seems to do this to ps

```
26214   0.0  0.2  3671444  39284 s012  S+   12:51AM   0:00.48 /Users/n/.nvm/versions/node/v4.4.7/bin/node --debug-brk /Users/n/P/node_modules/babel-watch/runner.js
26210   0.0  0.2  3104508  41884 s012  S+   12:51AM   0:00.64 node /Users/n/P/node_modules/.bin/babel-watch ./test.js
26208   0.0  0.5  3121008  82492 s013  S+   12:50AM   0:02.60 node /Users/n/P/node_modules/.bin/node-inspector
```

But this just stops at module.js:409 and then doesn't even run the test script when unpaused.

This is the closest I've gotten so far.

Ref: https://github.com/nodejs/node/blob/master/lib/child_process.js#L39

**Endnote**

As an aside, I'm curious why you decided not to read from .babelrc or package.json.

Thanks for putting this together. I find it to be the nicest approach out there for loading transpiled files.

**Comment by haraldrudell** [comment]
It's a design problem with babel-watch.

The file watching module, babel-watch.js, should never run in debug.

However, runner.js that should be with debug, is launched by babel-watch.js using fork, which means it will be in the same mode (debug/nodebug) as babel-watch.js. To fix that needs a code change.

In the mean time, one can put the following in your own code when debug is requested, sending a SIGUSR1 to your process which will put Node.js into debug mode after launch likeso:

`process.kill(process.pid, 'SIGUSR1')`

The way babel-watch 2.0.2 runs It also seems babel-cli steals argument from your script. It is common practice to separate using -- but I don't think that is done.

**Comment by nullxone** [comment]
The fork can be supplied the arguments using the execArgv property (in original post).

Thank you for the signal sending workaround, but I decided to go another way about this by putting together more basic tools.

**Method**

I'm using these scripts in package.json (can be run with `npm run ds1` and so on).

```
"scripts": {
  "di": "node-inspector -d=7000 -p=8000 --save-live-edit --hidden node_modules/",
  "ds1": "babel ./server -d ./build/server -s -w",
  "ds2": "nodemon --watch ./build/server --delay 100ms --debug=7000 ./build/server/main.js"
},
```

Running all three gives me quick feedback, and debugging with source maps.

**Comment by kmagiera** [comment]
Thanks @haraldrudell and @nullxone for the investigation on that.

Do you have any recommendation on the preferred workflow for debugging? I'd like to collect some feedback on how people use the debugger with node apps (I personally only use node-inspector connecting to the remote app, so it works fine for my workflow with babel-watch as well). And then we can think of some modifications that may improve "debugging" expirience with babel-watch

Thanks!

**Comment by kmagiera** [comment]
Have you guys tried using `--` option to escape parameters passed to the child process?

```
babel-watch -- src/main.js --debug=34532
```

**Comment by SupremeTechnopriest** [comment]
@kmagiera I just tried the above and I don't think it worked.  My start command looks like this 

```
NODE_PATH=server:src babel-watch --plugins transform-decorators-legacy -- server/server.js --debug=5858
```

Im attempting to attach to the debug process using vscode's debugger.

**Comment by kmagiera** [comment]
@SupremeTechnopriest thanks for the reply! How would that command look like when running with regular `node` or `babel-node`? I'm just not familiar with vscode at all (only tried that with webstorm) and don't know how does it connect with the running process

**Comment by SupremeTechnopriest** [comment]
With node only it would look like this.  It might have something to do with the order of the arguments. 

```
NODE_PATH=server:src node --debug=5858 server/server.js
```

**Comment by aknuds1** [comment]
I normally debug my Node app like so: `./node_modules/.bin/babel-node --debug-brk --inspect .`.

I can't see how to do the same with babel-watch however :/

**Comment by SupremeTechnopriest** [comment]
I submitted a PR #23 that adds a `--debug` option to the CLI.  It exposes the child process's debugger on the specified port.

**Comment by SupremeTechnopriest** [comment]
I originally had it working unmodified by using node to call `babel-watch` and setting the parent process's debugger, but there is a bug in nodejs where the child process tries to use the same port as the parent process.  

`node --debug=5858 ./node_modules/babel-watch/babel-watch.js app.js`

This is a no-op.  My first solution was to use `child-process-debug` from npm.  Adding that solved the port problem, but it started two debugger processes; parent:`5858` and child: `5859`, which isn't really what I wanted. 

``` bash
Debugger listening on port 5858
Debugger listening on port 5859
App listening on port 8080
```

I landed on adding a new `commander` flag for debugger.  This way only the child process is affected.  I think this is the best approach.

**Comment by SupremeTechnopriest** [comment]
@kmagiera I think its safe to close this issue.  Together we have covered all the debug scenarios. 😄

**Comment by kmagiera** [comment]
Great – closing this. Will be pushing an update to npm in few mins

**Comment by scarlac** [comment]
None of the options above will work today. `--debug` is deprecated and attempting to use `--inspect=0.0.0.0:9222` will be ignored and instead `--inspect` will be passed, meaning you cannot configure it. For programs running in Docker, this means inspector will not be able to connect since debugger only allows container-local connections. On top of that, pressing CTRL+C will not abort the process and you must kill the process manually to stop babel-watch.

Example:
```
14:16:52 ~/jobs/project ⚡️ node --inspect=0.0.0.0:9222 node_modules/.bin/babel-watch -- test.js
Debugger listening on ws://0.0.0.0:9222/0fdba86a-fafc-4178-9a25-004da4f2792e
For help see https://nodejs.org/en/docs/inspector
Starting inspector on 0.0.0.0:9222 failed: address already in use
^C^C^C
```
Nothing happens here, and node inspector can connect but will be unable to actually debug anything or even do simple console commands. I also tried switching around `--` so it was:
`node --inspect=0.0.0.0:9222 -- node_modules/.bin/babel-watch test.js` with no mentionable change in behavior. Same goes for `--debug` where I'm instead thrown a deprecation warning.

Any plans on improving this?

**Comment by evert** [comment]
We're also stuck on this. We need to be able to bind the inspector on `0.0.0.0`.

**Comment by maxtechera** [comment]
I'm facing the same issue, Binding to `0.0.0.0` is needed for debugging node apps inside Docker containers.

**Comment by mdhornet90** [comment]
This is also an issue for my project. Same use case, trying to debug a Dockerized app on 0.0.0.0.

**Comment by jhgaylor** [comment]
This has been fixed in master. I got the code by using `"babel-watch": "kmagiera/babel-watch"` in my package.json.

**Comment by kmagiera** [comment]
We are waiting for #95 to land, after that I'll publish a new update

**Comment by georgiosd** [comment]
@kmagiera did this ever get fixed and published? can't seem to be able to debug from vscode

**Comment by clintonmedbery** [comment]
Anyone ever get this to work? @kmagiera
