### ISSUE TITLE
"Error: Cannot find module" with .jsx files

### ISSUE THREAD

**Issue by crccheck** [kmagiera/babel-watch#21]
Trying to replace nodemon + babel-node with babel-watch, running with `babel-watch` gives an error when `babel-node` does not. I don't think the `--extension` option affects this but I threw it on just in case.

`babel-core` v6.14.0

should work, but does not:

```
$ node_modules/.bin/babel-watch src/index.js -e .js,.jsx
Error: Cannot find module './views/appFactory'
```

`babel-node` works:

```
$ node_modules/.bin/babel-node src/index.js
[18:18:23] Running server at 0.0.0.0:8000
```

Renaming `appFactory.jsx` to `appFactory.js` makes the error go away, but then I'd have to find all of them and this isn't my code.

**Comment by kmagiera** [comment]
@crccheck thanks for reporting! I'm assuming you're loading JSX files using standard methodologies ("require" or "import"), is that correct?

**Comment by crccheck** [comment]
Correct. I found this SO too that has the same info http://stackoverflow.com/questions/39429775/babel-watch-not-loading-jsx-files

**Comment by kmagiera** [comment]
Have you tried adding full extension to the `require` statement e.g.:

```
require('./views/appFactory.jsx')
```

or

```
import AppFactory from './views/appFactory.jsx'
```

**Comment by crccheck** [comment]
That does work, but I'm testing `babel-watch` in someone else's code and renaming things isn't an option.

**Comment by kmagiera** [comment]
@crccheck cool. Thanks for your help. I think I have a fix for the issue. Will send it out very soon and let you know once it's here

**Comment by kmagiera** [comment]
And the fix is ready here: https://github.com/kmagiera/babel-watch/commit/14eac0e3b5659f574ca5a2044ffa45139f746a3d

**Comment by kmagiera** [comment]
And I've just pushed an update to npmjs, please check 2.0.3-rc0 and reopen if you're still experiencing the issue

**Comment by crccheck** [comment]
It worked for me. Thanks for the speedy fix!

**Comment by kmagiera** [comment]
@crccheck thanks so much for reporting!
