### ISSUE TITLE
System files get generated

### ISSUE THREAD

**Issue by mrsimonemms** [kmagiera/babel-watch#24]
I'm using babel-watch (v2.0.2) with NodeJS (v6.5) and Docker compose (1.8.0) on a Mac and it works great - thanks.

The only issue I'm getting is that every time I run a command with babel-watch is that it generates a series of systems files in the root of my project.  These files appear to be sequential with the number increasing by one each day.  I've done quite a bit of investigation as I believe that babel-watch is what's creating them and it only happens on a Docker container.

These are the files generated today (from an `ls -la` command)

``` bash
prw-rw-rw-  1 semms  staff  0 21 Sep 09:57 116821-28-g6kgm4.l65h9cc8fr
prw-rw-rw-  1 semms  staff  0 21 Sep 10:00 116821-28-oxs06c.dkqtm1v2t9
prw-rw-rw-  1 semms  staff  0 21 Sep 09:35 116821-29-1n7nvjh.6lej0pb9
prw-rw-rw-  1 semms  staff  0 21 Sep 09:59 116821-29-60yxjk.smwxbf0f6r
prw-rw-rw-  1 semms  staff  0 21 Sep 10:01 116821-29-kzs2k9.ru65p9o1or
prw-rw-rw-  1 semms  staff  0 21 Sep 09:42 116821-54-z1ahkg.1d5onljtt9
```

I'm ok with babel-watch creating them, but I'd like to add the removal to my cleanup script. How is the file name generated so I can add a cleaner way of deleting them other than `rm 1168*`?

**Comment by kmagiera** [comment]
@riggerthegeek thanks for reporting. It is very strange that the files end up being saved in your project root. We use `os.tmpdir()` method for that, is the project root what the node process running in your docker container returns. One file is created per restart and we also delete the previous file when the app restarts, so there should never be more than one unless you kill the babel-watch process in which case it may not be able to perform the cleanup

**Comment by mrsimonemms** [comment]
Thank @kmagiera.

I've checked the result of `os.tmpdir()` in `/node_modules/.bin/babel-watch` (line 160) and it's coming out as `/opt/browserspy` (that being the name of my home directory in my Docker container).  Interestingly/annoyingly, when I run `node -e "console.log(require('os').tmpdir())"` in my container's command line, I get back `/tmp`.

I've created a fork and will see if I can identify why it's being a problem. I'll work out the cause and either put it here or create a pull request if relevant.

**Comment by mrsimonemms** [comment]
Yeah, this is definitely not an issue for you to fix.  I'm using npm scripts to run my packages and it seems that, in docker at least, the `npm run` appears to change the `TMPDIR` environment variable to the current directory.

I'll submit a PR with an addendum to the troubleshooting section, but this looks like an [npm bug](https://github.com/npm/npm/issues/4531)

**Comment by kmagiera** [comment]
@riggerthegeek thanks a lot for your investigation!
