### ISSUE TITLE
babel-watch creates temporary files that it doesn't clean

### ISSUE THREAD

**Issue by steelbrain** [kmagiera/babel-watch#28]
<img src="https://cloud.githubusercontent.com/assets/4278113/19462820/f1603b52-950c-11e6-8118-9948991a4647.png">

Each invocation of babel-watch creates a new temp file and it's never cleaned up. It would be nice if babel-watch would listen for `SIGTERM` even and syncly garbage collect all those files

**Comment by kmagiera** [comment]
@steelbrain thanks for reporting! Could it be a duplicate of https://github.com/kmagiera/babel-watch/issues/24 ? What is you OS setup?

**Comment by steelbrain** [comment]
I'm on macOS Sierra and here's my tmpdir

<img width="376" alt="screen shot 2016-11-08 at 10 20 56 am" src="https://cloud.githubusercontent.com/assets/4278113/20111450/2c44224c-a59d-11e6-9fa9-fe443e4d3373.png">

While it does look like a similar issue to that, I am still not sure how to fix it

**Comment by kmagiera** [comment]
Ah, I see now. You're correct that we can perhaps delete these files (one file gets created per application restart), but since the file size is 0, and also whenever babel-watch process is killed system will cleanup that directory automatically I wasn't considering it as a problem. Thoughts?

**Comment by steelbrain** [comment]
The files are zero byte correct, but the system does NOT clean up those files as they are stored in the root dir of the app being run and NOT in the cache dir.

If there's any more debug info I can provide, please let me know

**Comment by kmagiera** [comment]
@steelbrain Can you see this comment and confirm that you're seeing this issue only when running `babel-watch` with `npm run` https://github.com/kmagiera/babel-watch/issues/24#issuecomment-249154511

**Comment by steelbrain** [comment]
You are right. I see the npm was not fixed either. Thanks for helping me debug this, appreciated 👍

**Comment by steelbrain** [comment]
As a side note, could you look into using [`find-cache-dir`](https://www.npmjs.com/package/find-cache-dir) instead of `os.tmpdir()` to it this for the userbase of this package?

**Comment by kmagiera** [comment]
The thing is that we don't need a "cache" here but just a correct place to store temporary files. Cache would make those file persist across process reboots which is undersirable (sadly in your use case those files are kept in the FS anyways, but it's not like that for everyone)

**Comment by steelbrain** [comment]
Fair enough, I'll try to work it around in my app
