### ISSUE TITLE
run babel/node with a flag 

### ISSUE THREAD

**Issue by hareeqi** [kmagiera/babel-watch#34]
Thank you this is exactly what we need but we are having a problem trying to run babel/node with a flag. Can you point us on how to achieve that with babel-watch. Thanks

with node: i can do this
```
node --harmony-async-await  server.js
```

with babel node:
```
babel-node --harmony-async-await  server.js
```

with nodemon:
```
nodemon --exec babel-node --harmony-async-await server.js
```

**Comment by kmagiera** [comment]
@hareeqi thanks for reporting! There is a PR aiming at this issue #31

**Comment by STRML** [comment]
Use `NODE_OPTIONS`. See d56971ce9ad7d9182911e00cb92ce6598b2a30e1
