### ISSUE TITLE
Readline simply doesnt work with babel-watch

### ISSUE THREAD

**Issue by azarus** [kmagiera/babel-watch#35]
Since the watched app runs in a seperate process readline doesn't work, also no stdin is available for the process.

Would it be possible to forward the stdin to the sub process?

Thanks.

**Comment by azarus** [comment]
Given the following example
```

const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('What do you think of Node.js? ', (answer) => {
  // TODO: Log the answer in a database
  console.log(`Thank you for your valuable feedback: ${answer}`);

  rl.close();
});
```

 the output result would be:

```
babel-node test.js
What do you think of Node.js? test
Thank you for your valuable feedback: test
```

But the result is:

```
babel-watch test.js
What do you think of Node.js? test
```

Note that the readline funciton doesn't call the callback. So the _Thank you for your valuable feedback: test_ is not printed on the screeen..

**Comment by azarus** [comment]
I did some research i think this is related to this issue:
https://github.com/nodejs/node-v0.x-archive/issues/1742

**Comment by azarus** [comment]
Looks like this code part causes the issue, since its switching the stdin input to the fork and then back to the main process.
`const stdin = process.stdin;
stdin.setEncoding('utf8');
stdin.on('data', (data) => {
  if (String(data).trim() === RESTART_COMMAND) {
    restartApp();
  }
});`

Also applications should not use babel-watch in production, so this should be removed from the code or the all stdin events should be passed to the fork.

**Comment by kmagiera** [comment]
@azarus I think it would be the best to add a new flag that would disable stdin capturing. I know that the most frequent use case for babel watch is to use it with web-based application which does not require to read anything from STDIN, and then it's pretty handy to be able to restart the app from the command line (by typing `rs`) as it is also something that people using nodemod are familiar with

**Comment by aymericbeaumet** [comment]
I'm also developing a CLI app with a shell-like prompt, and this is currently not usable. The overhead of listening on `process.stdin` makes it too laggy for real typing.

Offering a `--no-stdin` flag sounds reasonable to me 👍 

As a temporary solution I have removed [those lines](https://github.com/kmagiera/babel-watch/blob/3b9f886e262c343430dd868046943be5112227e8/babel-watch.js#L138-L145) from my local node_modules, and everything works fine.

**Comment by hmmhmmhm** [comment]
It still same problem exist :(

**Comment by itsezc** [comment]
+1 Still exists
