### ISSUE TITLE
babel-node Restart doesn't kill the previous process - Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by ghost** [kmagiera/babel-watch#36]
Thank you for babel-watch. I am using it with babel-node, but it seems like every time I save, it cannot start the server again.

I just use the simplest command possible "babel-watch src".

**Comment by kmagiera** [comment]
@time-traveling-pineapple you should call `babel-watch` with the application main JS file, not with a directory name. I hope that resolves your issue. Otherwise feel free to reopen it
