### ISSUE TITLE
config file switch 

### ISSUE THREAD

**Issue by ieow** [kmagiera/babel-watch#4]
suggestion for config file switch for more clean config

**Comment by kmagiera** [comment]
@ieow what do you mean by "config file switch" can you explain this/give some example or use-case?

**Comment by ieow** [comment]
example:
babel-watch -c configFile.json

in configFile,json
{
    watch : [ watchDir, ],
    exclude : [ excludeDir, ],
}

**Comment by kmagiera** [comment]
I've just pushed new version that does no longer require you to specify directories you like to watch. Instead you just provide the main node script name and babel-watch figures out which files is your app including and watch for changes in those files.

As for the remaining options, I believe it's not necessary to have a separate config for those as majority of options are just switches for babel (like `--presets` etc.), in which case I'd recommend to just use `.babelrc` which works just fine with `babel-node`. Another benefit of having that in `.babelrc` is that you can share this config in case you build your app using `babel-cli` for production.
