### ISSUE TITLE
babel-watch --present env index.js not work

### ISSUE THREAD

**Issue by TangMonk** [kmagiera/babel-watch#40]
throw following error:

```
$ ./node_modules/.bin/babel-watch --presets env server.js

/Users/tangmonk/Documents/mygit/nodejs/hotel_didi_car/server/api/index.js:9
        handler: async (request, reply) => {
        ^
ReferenceError: regeneratorRuntime is not defined
```

If i try to use multi presents:

```
$  ./node_modules/.bin/babel-watch --presets es2015 stage-3 server.js

Error: Cannot find module '/Users/tangmonk/Documents/mygit/nodejs/hotel_didi_car/stage-3'
    at Function.Module._resolveFilename (module.js:470:15)
```

**Comment by hareeqi** [comment]
currently babel watch doesn't support unknown options, I believe your issue, like mine, should be fixed with this PR https://github.com/kmagiera/babel-watch/pull/31

**Comment by TangMonk** [comment]
@hareeqi thanks for your reply, I just wanna to use Async/Await syntax

**Comment by TangMonk** [comment]
@hareeqi I found solution in #26

**Comment by STRML** [comment]
`babel-watch` can't be configured this way. Use configuration files as documented at https://babeljs.io/docs/en/configuration.
