### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by lucleray** [kmagiera/babel-watch#41]
I've added `babel-watch` to my project.

I've created a very simple `index.js` file :
```javascript
// very simple code, just to test
console.log('ok')
```

I've started `babel-watch index.js` with an `npm run` script and I get this in the console when I save some change in my `index.js` file :
```
>>> RESTARTING <<<
(node:36053) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
ok
```

Can you tell me how to hide this warning ?
I wonder if it's generated by the `babel-watch` code.

**Comment by ryancole** [comment]
Yup, same warning here.

**Comment by yormi** [comment]
Simply adding an function doing nothing here:
https://github.com/kmagiera/babel-watch/blob/master/babel-watch.js#L207

and here:
https://github.com/kmagiera/babel-watch/blob/master/babel-watch.js#L211

to show that we haven't forget to "handle" the asynchronicity does the job.

**Comment by ghost** [comment]
Has this been released on npm? I'm still getting the warning with v2.0.6. I assume not since the latest release is from 31 jan and the commit that fixes it is from 9 feb.
