### ISSUE TITLE
Problem with autowatch !?

### ISSUE THREAD

**Issue by yormi** [kmagiera/babel-watch#43]
Ok so, the second problem I encountered which can be easily workaround but still deserves an issue I think is that the autowatch doesn't work more than once per file.

With the same setup than in this issue: https://github.com/kmagiera/babel-watch/issues/42

So when I save a file, say `index.js`, the app restarts twice in a row as mentioned in the issue above. But then, if I change the same file, `index.js` (by changing the console.log text for instance) it does not restart.

Then if I go just save `aFileToRequire.js`, the app restarts (even wihtout any modif)... at least the first time. The second time I save, with or without modifs, nothing happens.

Since there's no more file in this small project, I can't restart it without `'rs'` from there.

The workaround is using the `babel-watch --watch . ` and then it works as expected.

Am I doing something wrong ?

Let me know you need more info :)

**Comment by SystemParadox** [comment]
I also have this issue (babel-watch 2.0.7), on Linux Mint, node 6.14.2.

Using the `-L` option appears to solve the issue. I have no idea what's up with the default file watcher system. It's a normal ext4 filesystem.

**Comment by STRML** [comment]
This is no longer an issue to my knowledge as of `7.1.0`, due to chokidar upgrades and built-in debouncing.
