### ISSUE TITLE
Crashes after restart: First argument must be file descriptor

### ISSUE THREAD

**Issue by andrew-3kb** [kmagiera/babel-watch#47]
Node version: 6.9.5
Platform: Linux (running in docker through this image: https://hub.docker.com/_/node/)
babel-watch version: 2.0.5

I can start babel watch and it works fine, will restart on changes successfully a few times and then when it tries to restart for the 2-6ish time, it will crash with the error:

```
/app/node_modules/babel-watch/babel-watch.js:298
          throw error;
          ^

 TypeError: First argument must be file descriptor
    at TypeError (native)
    at Object.fs.writeSync (fs.js:786:20)
    at error (/app/node_modules/babel-watch/babel-watch.js:289:12)
    at handleFileLoad (/app/node_modules/babel-watch/babel-watch.js:172:7)
    at ChildProcess.app.on (/app/node_modules/babel-watch/babel-watch.js:283:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I can then restart it and it will work fine again for a bit, rinse and repeat.

I have been using babel-watch for a while now and never had this problem before.

**Comment by darobin** [comment]
This _seems_ to happen to me more when the changes have come in short succession (eg because a linked dependency has rebuilt, changing many files at once). But I can't quite promise it's only then, it might be an effect from the number of restarts that triggers.

**Comment by chris-garrett** [comment]
I reverted to 2.0.4. Still crashes in docker but it's far less frequent.

**Comment by mikabytes** [comment]
This happens to me as well.

**Comment by steelbrain** [comment]
Any updates on this? Every time this happens I have to go into the Activity monitor and kill the spawned node process as it hogs 100% of a core

**Comment by steelbrain** [comment]
A fix is up in #68

**Comment by tony1223** [comment]
This is really annoying for fixing this in code manually, could we have a new release with the fix?

**Comment by rubycut** [comment]
Any eta on this?

**Comment by henriquesosa** [comment]
Any updates?

**Comment by steelbrain** [comment]
Not to hijack the thread but I ended up writing my own babel CLI (with caching) that supports running apps like `babel-watch`. You can find it at https://github.com/steelbrain/babel-cli
and run it like

```
sb-babel-cli src -o lib -x lib/server
```
