### ISSUE TITLE
Error about 'import' ...not loading babelrc?

### ISSUE THREAD

**Issue by loudwinston** [kmagiera/babel-watch#5]
I'm getting the following error 

Command `babel-watch --watch ./client/src --watch ./webpack ./bin/server.js`

```
/Users/loudwinston/testapp/bin/server.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
```

My `.babelrc` has `"presets": ["react", "es2015", "stage-0"],`

Does `babel-watch` load the `.babelrc` from the current working directory?

**Comment by kmagiera** [comment]
@loudwinston `babel-watch` will only transpile files that are under "watch" paths. In your case file `./bin/server.js` is not being watched (it's neither under `./webpack` nor `./client/src`.

In order for this to work you'll need to add `--watch ./bin/server.js` to you command so it look like this:

```
babel-watch --watch ./client/src --watch ./webpack --watch ./bin/server.js ./bin/server.js
```
