### ISSUE TITLE
babel-watch can't find "./package.json" 

### ISSUE THREAD

**Issue by ceruberu** [kmagiera/babel-watch#54]
In node_modules/.bin/babel-watch line 38
const pkg = require('./package.json');

My docker image can't run babel-watch because it cant find ./package.json
and there is no ./package.json file in .bin directory.

But I tried to run it in my local and I can find it when I console.log(pkg)
So when exactly is this package.json made???

**Comment by STRML** [comment]
Given that `node_modules/.bin` contains symlinks, I can't see how this happens. Please re-open if you are still experiencing this issue.
