### ISSUE TITLE
babel-watch unexpected token but babel-node works fine

### ISSUE THREAD

**Issue by olypros** [kmagiera/babel-watch#56]
`NODE_ENV=production node_modules/.bin/babel-node --presets react,es2015 src/server.js`
This command dosent gives me any error (babel node) but  

`NODE_ENV=production node_modules/.bin/babel-watch --presets react,es2015 src/server.js`
This command gives me error (babel-watch)

Undexpected token at 

`<Route  >
...`

**Comment by nazimjamil** [comment]
Have you set your `.babelrc` presets to es2015?

**Comment by STRML** [comment]
Babel options are unfortunately not supported as cli args. Use `.babelrc`, `package.json`, or `babel.config.js` instead.
