### ISSUE TITLE
[Enhancement] Please add option for restart text & separators

### ISSUE THREAD

**Issue by mrpotatoes** [kmagiera/babel-watch#57]
It would be nice to have the option to change the `>>> RESTARTING <<<` text and add some separation between the restarts.

Separators can be newlines or some string that we can choose.

**Comment by STRML** [comment]
This was added in 85e4af0c63d1604c735c6e8e29ea39d7276c6ff5 and enhanced in 1e5becbf87b82d4840a0f754e6a5c9d321666142.
