### ISSUE TITLE
Option --debug-brk doesn't work

### ISSUE THREAD

**Issue by sluchznak** [kmagiera/babel-watch#58]
Hello.
If specify `--debug-brk` then app stop running:
```
node_modules/.bin/babel-watch src/server.js -I --debug-brk
```
If only `--inspect` option - all fine:
```
node_modules/.bin/babel-watch src/server.js -I
```

In babel-node options `-I --debug-brk` works well.

Node version: `7.9.0`

**Comment by tyronedougherty** [comment]
+1, did you find a solution to debug your ES6 app?

**Comment by STRML** [comment]
`--debug-brk` and `--inspect` together was required in Node 6, but after Node 6 there is `--inspect-brk`. We don't plan to support these options together as Node 6 is long gone.

I have tested and ensured that `--inspect` and `--inspect-brk`, with and without the `[address]` argument, work as expected.
