### ISSUE TITLE
failing in docker container

### ISSUE THREAD

**Issue by stringa** [kmagiera/babel-watch#59]
I've gone ahead and added the -L option to babel-watch.

I seem to get the following error once I change a JS file

webrtc.server.1    | >>> RESTARTING <<<
webrtc.server.1    | Debugger listening on port 9229.
webrtc.server.1    | Warning: This is an experimental feature and could change at any time.
webrtc.server.1    | To start debugging, open the following URL in Chrome:
webrtc.server.1    |     chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/b18dea6d-3597-4911-a03d-991793729cf4
webrtc.server.1    | (node:18) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
webrtc.server.1    | 
webrtc.server.1    | /app/node_modules/depd/index.js:25
webrtc.server.1    | var basePath = process.cwd()
webrtc.server.1    |                        ^
webrtc.server.1    | Error: ENOENT: no such file or directory, uv_cwd
webrtc.server.1    |     at Object.<anonymous> (/app/node_modules/depd/index.js:25:24)
webrtc.server.1    |     at Module._compile (module.js:571:32)
webrtc.server.1    |     at Module._extensions..js (module.js:580:10)
webrtc.server.1    |     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-watch/runner.js:63:7)
webrtc.server.1    |     at Module.load (module.js:488:32)
webrtc.server.1    |     at tryModuleLoad (module.js:447:12)
webrtc.server.1    |     at Function.Module._load (module.js:439:3)
webrtc.server.1    |     at Module.require (module.js:498:17)
webrtc.server.1    |     at require (internal/module.js:20:19)
webrtc.server.1    |     at Object.<anonymous> (/app/node_modules/http-errors/index.js:15:17)

I am not able to find much online and the babel-watch documentation makes it think this should work.

**Comment by maryqygao** [comment]
Has there been any updates on this? Experiencing the same problem mounting into docker in the latest version (2.0.7).

**Comment by STRML** [comment]
That's super weird. If you're still experiencing this, could you please try the latest version?

**Comment by STRML** [comment]
Closing pending clarification.
