### ISSUE TITLE
stdout redirect and rewrite

### ISSUE THREAD

**Issue by James2516** [kmagiera/babel-watch#61]
Config: `"start": "babel-watch script.js > out.txt"`.

When i run `npm start`, I want the output from script.js to rewrite to instead of appending to `out.txt` whenever the script is re-run.

I tried `"babel-watch script.js >! out.txt"` as well as `>|`, both don't work.

Perhaps I can config babel-watch such that it runs `rm out.txt` before running `script.js`?

**Comment by STRML** [comment]
Sorry, this isn't something we're going to support. I suggest chaining the commands:

```
"start": "rm -f out.txt && babel-watch script.js > out.txt"
```
