### ISSUE TITLE
Seeking Maintainer?

### ISSUE THREAD

**Issue by esetnik** [kmagiera/babel-watch#71]
Is this project actively being maintained? It looks like there are several open PRs that offer significant improvements to the codebase.

**Comment by chris-garrett** [comment]
I came here to ask the same thing :)

**Comment by coreyleelarson** [comment]
It doesn't look like it. One of those PRs is mine :)

**Comment by sarendipitee** [comment]
@kmagiera Are you alive? :)

Looks like a lot of people are interested in this lib and keeping it up to date. A lot of nice PRs out there, we at least need someone to hit yolo hit merge on some of these if you don't have the time @kmagiera.

Any volunteers?

Pinging some people who have active forks ahead of kmagiera/master that might be interested.

@coreyleelarson @good-idea @ChibiBlasphem @Merri @esetnik @esetnik @monathur 

If we still don't hear from @kmagiera perhaps we should select someone's fork to be the new actively developed, add some additional maintainers and go from there.

**Comment by ghost** [comment]
My fork provides compatibility for Babel 7, however it's based on @good-idea 's fork which is still waiting to merge as #83

**Comment by kmagiera** [comment]
I'm sorry for not doing a good job maintaining this repo. I haven't been actively using it for a while now and was hoping that updates coming to node are going to render it obsolete.

As it seems there are still plenty of people relying on this project I'm happy to hand it off to someone else. I tried that in the past but that didn't work out as I think that person has also vanished.

Thanks @JonDum for coming up with the list of people who are potentially interested. Also wanted to thank everyone for their contribution and apologise for the inconvenience my lack of response has caused.

@monathur as it looks like your fork is the most actively maintained I'd love to give you admin access to the main repo. If you would like to work on the next release I'd be happy to give you npm access as well. What do you think?

**Comment by kmagiera** [comment]
Hey @esetnik as it appears process of finding someone to take over the maintenance of this project would you be open to help list PRs that are of good quality and ready to merge?
I think the community will much appreciate getting an update but since I don't use this project it is hard for me to judge on usefulness and quality of the PR. What I can do though is to get things merged and put out a new release before we can find someone who would be able to take over that process too.

**Comment by esetnik** [comment]
@kmagiera no need to apologize. You've done a great job creating free software for us to use and enjoy. I don't have time to devote to reviewing PRs for this project at the moment. I've got a 👶coming in less than a month and I think i'll have my hands full getting ready for that. The best path forward for `babel-watch` is to find a maintainer and have them review all the outstanding PRs. Alternatively contact the `@babel` team and see if they are interested in bringing this project into `@babel/core`. In my opinion, the functionality of this library is necessary for local babel development and should ship with babel itself.

**Comment by ChibiBlasphem** [comment]
Hello =)
It's been two month already, do we have an idea of the new maintainer ?

Edit: At the moment I have all my npm package referencing @monathur repo. I don't think this is the good way to do it.

**Comment by sibelius** [comment]
you should add all these people that commented in this issue, so the project could move on

**Comment by ghost** [comment]
@kmagiera  I think I can handle being a new maintainer since I use this package in some of my projects, so I really care about babel-watch's functionality and compatibility. I may, however, need help of the community in maintaining the repository, because this would be my first such a large open source package. In my paid work I write only closed source code, and privately published projects are quite small so far 😄 

Btw: Mówisz po polsku, Krzysztofie?

**Comment by kmagiera** [comment]
Hey @monathur !

Mówie po polsku :)

I think if you are motivated to work on this project and you use it daily that's a great mix and I look forward to welcoming you as a maintainer.

I invited you as a collaborator. I think the good place to start would be by looking over PRs and trying to merge things you find important and inline with the goals you have for this project. Once you are ready to publish next release please ping me here or DM me on twitter (https://twitter.com/kzzzf) and I'll add you to npm too.

Good luck and I hope that thanks to you this project will become much better!

**Comment by Justkant** [comment]
Hi, I can help maintaining too.

I've got a [fork](https://github.com/Justkant/babel-watch) which fixes some issues.
I also created some [issues](https://github.com/Justkant/babel-watch/issues) to refactor the codebase and improve performance.

**Comment by felixk42** [comment]
Hyped to see @monathur taking this project on, it's been really useful.

Now can we get a new release with the shiny new changes in it :P ?

**Comment by ghost** [comment]
I'm working on new release, however I need to get into standard of code and discuss some things with @kmagiera to be able to provide you the best possible quality of the next version ;)

**Comment by coreyleelarson** [comment]
@monathur @kmagiera - If you need another maintainer, I'd be happy to help!

**Comment by olalonde** [comment]
+1 for new maintainer... getting `warning " > babel-watch@2.0.7" has unmet peer dependency "babel-core@6.5.1 - 6.6.0 || ^6.6.x".`

**Comment by STRML** [comment]
@kmagiera Our organization is also willing to take this on - we have a team of devs who use babel-watch regularly and would be willing to review & merge PRs. If you're interested, please check out my profile and BitMEX, and we can sort out being added to the repo & npm.

**Comment by kmagiera** [comment]
Hey @STRML ! Very glad to hear you are willing to give it a try. Could you please DM me on twitter (https://twitter.com/kzzzf) where we can discuss how to approach this (if you don't use twitter we can figure out some other way to communicate)

**Comment by phawxby** [comment]
@STRML @kmagiera @Justkant did anyone else takeover maintainer status? It looks like monathur did but has since deleted his account.

**Comment by Justkant** [comment]
Hey @phawxby, I unfortunately didn't takeover maintainer status.
We still use my fork (https://github.com/Justkant/babel-watch) on some legacy projects, but we're moving away from `babel-watch`

**Comment by phawxby** [comment]
Thanks @Justkant. What are you replacing babel-watch with?

**Comment by Justkant** [comment]
We use Typescript for the backend now and use https://github.com/gilamran/tsc-watch/ to do the same job as `babel-watch` for `tsc` (alternatives: https://github.com/whitecolor/ts-node-dev)
We are also moving away from `docker-compose` by using `skaffold` instead but this is where we need improvement, I tried Bazel with skaffold as it can better cache and parallelize builds for micro-services but it doesn't support native modules yet when cross-compiling

**Comment by phawxby** [comment]
@Justkant great, thanks for the insight!

**Comment by STRML** [comment]
Finally got publish access. `7.1.0` is now published and we're back on the ball.

If anyone else would like to contribute, please reach out.
