### ISSUE TITLE
[Question] How do I specify an output folder?

### ISSUE THREAD

**Issue by AshCoolman** [kmagiera/babel-watch#74]
I might be blind, but I cant see the option

**Comment by Spotnyk** [comment]
I'm having the same issue. @AshCoolman Maybe we're blind together :)

**Comment by eh-am** [comment]
Had the same question, ended up using `babel src -d dist --watch`

**Comment by STRML** [comment]
I'm not sure I understand the question. Output to where? This isn't intended to drop files on disk, it compiles in memory then runs from there. I'm closing for now, but please re-open if you have a more pointed question.
