### ISSUE TITLE
Supports for babel 7.0

### ISSUE THREAD

**Issue by shtse8** [kmagiera/babel-watch#75]
Any plans to support babel 7.0?

**Comment by Evanion** [comment]
me want ☹️

**Comment by sergivillar** [comment]
any update on this?

**Comment by hpgmiskin** [comment]
Thanks to the work of @good-idea and @monathur it is possible to install a version of `babel-watch` that works with Babel 7 using this command.

```
yarn add https://github.com/monathur/babel-watch.git --dev
```

**Comment by loris** [comment]
I have been using @monathur fork since the release of babel 7 and it is working great!
Any update on merging the fork in @kmagiera repo?

**Comment by hpgmiskin** [comment]
@loris take a look at issue #71 as this integration will likely happen when maintainer is changed

**Comment by ghost** [comment]
@loris Today, I will refactor my fork and fix some minor bugs and then I will create a PR, so there's a chance for a quick release of the new version compatible with Babel 7

**Comment by JeffLuong** [comment]
@kmagiera @monathur any idea when this will be released? Since at this point we'll still need to use the the fork

**Comment by zyhou** [comment]
Any update ? @kmagiera

**Comment by philihp** [comment]
@kmagiera ping?

**Comment by kmagiera** [comment]
Hey! I just published a new release with all the stuff @monathur merged upstream. I think babel7 stuff is there too. 

@monathur can you please ping me on twitter or email next time you want me to publish a release? I'd like to pass on the publish right to npmjs to you at some point too.

**Comment by philihp** [comment]
2.0.8 does not have Babel 7 support. Still specifies a peer dependency of Babel 6, and still looks for babel.util.*

**Comment by kmagiera** [comment]
thanks @philihp for the info – I was under the impression @monathur has merged all of his changes upstream already. If there are any outstanding changes that he might've missed can you please submit a PR with that and I'll cut another release shortly.

**Comment by palfrey** [comment]
@kmagiera https://github.com/kmagiera/babel-watch/compare/master...monathur:master shows a bunch of changes

**Comment by jacobwgillespie** [comment]
If you pull in the changes from https://github.com/monathur/babel-watch, you'll also want to pull in https://github.com/monathur/babel-watch/pull/2 since `master` is missing a lodash import.

**Comment by kmagiera** [comment]
anyone here interested in sending a PR that'd include necessary changes from @monathur's fork?

**Comment by pfhayes** [comment]
@kmagiera https://github.com/kmagiera/babel-watch/pull/95

**Comment by kmagiera** [comment]
Thanks @pfhayes! I left one comment on your PR, please take a look when you find some time

**Comment by kmagiera** [comment]
FYI babel-watch@7.0.0 is out with babel7 compatibility updates by @monathur and @pfhayes 🙌
