### ISSUE TITLE
Weird behavior and a small question?

### ISSUE THREAD

**Issue by SvitlanaShepitsena** [kmagiera/babel-watch#77]
Guys, first of all thank you for you package as nodemon and babel-node works only with CTRL+C, CTRL+C. 
With a babel-watch I have a strange behavior in Reactjs Isomorphic App -  when I just have such script:
    `./node_modules/.bin/babel-watch server/server.js`
When I change server files - first change is perfectly works. However after first restart the file is probably removed from watch. Any subsequent change (on that file) has not effect on restart? Any idea why? 

I found a solution to the question 1.
      `./node_modules/.bin/babel-watch --watch=\"units/*\" server/server.js"`
This works perfectly when I have 1 folder units, but I could not find a way to add several folders to the watch. For example,  that script does not work. 
    `./node_modules/.bin/babel-watch --watch=\"units/*\",\"server/*\" server/server.js"` 

And tried all possible blob variations, probably my understanding there is not deep :-).

**Comment by STRML** [comment]
Hi. This is pretty old and file watching is different in `7.x`. I'm going to close this for now, but if you're still having this problem please holler.
