### ISSUE TITLE
Add notification after restart

### ISSUE THREAD

**Issue by christopher-francisco** [kmagiera/babel-watch#79]
Hey guys, loving this module so far. I want to contribute with notifications for when the server restarts, something like:

```
-------------------
| babel-watch        |
|                              |
| App Restarted     |
-------------------
```

Let me know what you think.

**Comment by STRML** [comment]
This can now be done via the `--before-restart` hook. For example:

```
babel-watch --before-restart="echo 'restarted!' | terminal-notifier" app.js
```
