### ISSUE TITLE
Next.js

### ISSUE THREAD

**Issue by gcfabri** [kmagiera/babel-watch#81]
I am working on a project using Next.js with a custom Express server and this is the script that I use to reload on changes both server and client side. I had experiencied babel-watch on another projects and it is fastest that this combination but I cant achieve the same behavior using Next.js.

nodemon -w server server/server.js --exec babel-node --presets env

**How can I do the same using babel-watch?**

**Comment by STRML** [comment]
I'm not really sure what you're asking here, so I'm going to close pending clarification.
