### ISSUE TITLE
Running experimental features? 

### ISSUE THREAD

**Issue by ekeuus** [kmagiera/babel-watch#98]
I would like to pass "--experimental-worker" to the internal node instance to enable worker_threads.

What are the options to do so? I tried adding the flag to allowed params, but it still fails at:

`server-node_1  | Error: Cannot find module 'worker_threads'
server-node_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
server-node_1  |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
server-node_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
server-node_1  |     at require (internal/modules/cjs/helpers.js:22:18)
server-node_1  |     at Object.<anonymous> (/var/www/node_modules/microjob/dist/worker-pool.js:7:26)
server-node_1  |     at Module._compile (internal/modules/cjs/loader.js:701:30)
server-node_1  |     at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
server-node_1  |     at Object.require.extensions.(anonymous function) [as .js] (/var/www/node_modules/babel-watch/runner.js:64:7)`

**Comment by IlyaSemenov** [comment]
You can use `NODE_OPTIONS` to pass arbitrary node.js options, for instance:

```bash
NODE_OPTIONS="--experimental-worker" babel-watch server.js
```
